1) SELECT * FROM SAILORS WHERE SAILORS_NAME LIKE "J%";
3)SELECT DISTINCT S2.SAILORS_NAME
FROM RESERVES R1
JOIN SAILORS S1 ON R1.SAILOR_ID = S1.SAILORS_ID
JOIN BOATS B1 ON R1.BOAT_ID = B1.BOAT_ID
JOIN BOATS B2 ON B2.COLOR = B1.COLOR
JOIN RESERVES R2 ON R2.BOAT_ID = B2.BOAT_ID
JOIN SAILORS S2 ON R2.SAILOR_ID = S2.SAILORS_ID
WHERE S1.SAILORS_NAME = 'JOHN'
ORDER BY S2.SAILORS_NAME;

10)SELECT DISTINCT S.SAILORS_NAME
FROM SAILORS S
WHERE NOT EXISTS (
    SELECT B.BOAT_NAME
    FROM BOATS B
    WHERE B.BOAT_NAME LIKE 'SEA%'
    AND NOT EXISTS (
        SELECT 1
        FROM RESERVES R
        WHERE R.BOAT_ID = B.BOAT_ID
        AND R.SAILOR_ID = S.SAILORS_ID
    )
);

4)SELECT S.SAILORS_NAME
FROM SAILORS S
JOIN RESERVES R ON S.SAILORS_ID = R.SAILOR_ID
GROUP BY S.SAILORS_NAME
HAVING COUNT(R.BOAT_ID) > 1;


5)SELECT LOCATION
FROM MARINAS
GROUP BY LOCATION
HAVING COUNT(MARINA_ID) > 2;


6) SELECT B.BOAT_NAME
FROM BOATS B
JOIN RESERVES R ON B.BOAT_ID = R.BOAT_ID
GROUP BY B.BOAT_NAME
HAVING COUNT(DISTINCT R.SAILOR_ID) > 1;

7)SELECT M.MARINA_NAME, AVG(S.SAILORS_AGE) AS AVERAGE_AGE
FROM MARINAS M
JOIN RESERVES R ON M.MARINA_ID = R.MARINA_ID
JOIN SAILORS S ON R.SAILOR_ID = S.SAILORS_ID
GROUP BY M.MARINA_ID, M.MARINA_NAME
ORDER BY AVERAGE_AGE DESC;


9)SELECT DISTINCT S.SAILORS_NAME
FROM SAILORS S
LEFT JOIN RESERVES R ON S.SAILORS_ID = R.SAILOR_ID
WHERE S.RATING >= 8 OR R.BOAT_ID = 'B204';


8)SELECT DISTINCT B1.BOAT_NAME
FROM BOATS B1
JOIN BOATS B2 ON B1.COLOR = B2.COLOR AND B1.BOAT_ID <> B2.BOAT_ID;



